Add docs for tests scenarios
threefoldtech/js-sdk pull request #1407
Opened 2020-10-11 14:44 UTC by AhmedHanafy725

### Description

- Fix docstring of the tests
- Add tests scenarios to repo's docs

### Related Issues
#1316

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2020-10-11 14:50 UTC, waleedhammam requested changes

2020-10-11 14:50 UTC, waleedhammam commented on tests/base_tests.py
> +        j.data.idgenerator.nfromchoices(10, string.ascii_letters)
Should we return in here?

2020-10-11 15:09 UTC, waleedhammam approved these changes

2020-10-11 15:20 UTC, xmonader commented
Love it! please check if the following improvements are possible 

- add it as a task in Makefile to autogenerate 
- add an entry for each file in a main README.md to navigate easily

2020-10-12 14:28 UTC, xmonader approved these changes

2020-10-12 14:28 UTC, merged