add wait for create repo
threefoldtech/js-sdk pull request #1459
Opened 2020-10-19 11:19 UTC by mhost39

### Description
Test coverage for Github

### Related Issues
https://github.com/threefoldtech/js-sdk/issues/1314

2020-10-19 17:03 UTC, waleedhammam commented on tests/clients/github/test_github.py
> +                sec -= 1
What is sec ? A counter ? Maybe we can replace while with for then

2020-10-19 17:03 UTC, waleedhammam commented on tests/clients/github/test_github.py
> +            if repo.name not in str(self.client.get_repos()):
Here too

2020-10-20 14:25 UTC, waleedhammam requested changes

2020-10-20 14:25 UTC, waleedhammam commented on tests/clients/github/test_github.py
> +                sec -= 1
nope, that's not the correct for for loop :)

2020-10-21 11:24 UTC, AhmedHanafy725 requested changes

2020-10-21 11:24 UTC, AhmedHanafy725 commented on tests/clients/github/test_github.py
> +        for i in range(sec):
In case of we don't need the counter variable, it's better to use `_` instead.
```suggestion
        for _ in range(sec):
```

2020-10-21 11:24 UTC, AhmedHanafy725 commented on tests/clients/github/test_github.py
> +        for i in range(sec):
```suggestion
        for _ in range(sec):
```

2020-10-22 16:47 UTC, AhmedHanafy725 approved these changes

2020-10-22 20:59 UTC, waleedhammam approved these changes

2020-10-22 23:32 UTC, merged