add new tools to compute how much cloud units is used by a workload
threefoldtech/js-sdk pull request #1492
Opened 2020-10-22 14:36 UTC by zaibon

### Description

Add a new `consumption` section in `j.tools.zos` which allow to compute how much cloud units are consumed by a workload object

### Changes

- Add new module in j.tools.zos
- Add `resource_units` methods on all the workloads model

### Related Issues

fixes #1423

### Checklist

- [x] Tests included
- [ ] Build pass
- [ ] Documentation
- [x] Code format and docstrings

2020-11-02 20:34 UTC, xmonader commented on jumpscale/clients/explorer/test_models.py
> +from .models import DiskType, Container, Volume, ZdbNamespace, K8s
can we move the tests into tests/clients/explorer instead

2020-11-10 11:37 UTC, LeeSmet requested changes
I don't really like the idea of giving 50GB of SSD for containers for free, but it is what it is I guess

2020-11-10 11:37 UTC, LeeSmet commented on jumpscale/clients/explorer/models.py
> +        resource_units.mru = round(cap.memory / 1024)
mru is a float so rounding here only makes sense if we want to limit the amount of significant digits like it is done on the next line imo

2020-11-10 14:36 UTC, LeeSmet approved these changes
lgtm

2020-11-11 11:28 UTC, xmonader approved these changes

2020-11-11 11:28 UTC, xmonader approved these changes

2020-11-11 11:28 UTC, merged