Update ubuntu deploy script to use management network with the new ip
threefoldtech/js-sdk pull request #1590
Opened 2020-11-02 11:43 UTC by RafyAmgadBenjamin

### Description

Update ubuntu script to use `management` network with the correct IP, if we are not able to load the network then we create a new one.
### Changes

List of changes this PR includes
examplescripts/ubuntu.py

### Related Issues

List of related issues
https://github.com/threefoldtech/js-sdk/issues/1578

2020-11-02 11:47 UTC, ashraffouda approved these changes

2020-11-02 11:53 UTC, m-motawea commented
you need to check if the selected node is already part of the network or not. if it isn't, you need to find a free range and add it to the network. if it is, you need to find a free ip address from that node's range and use it for deployment

2020-11-02 11:53 UTC, m-motawea requested changes
you need to check if the selected node is already part of the network or not. if it isn't, you need to find a free range and add it to the network. if it is, you need to find a free ip address from that node's range and use it for deployment

2020-11-04 06:59 UTC, m-motawea approved these changes

2020-11-04 06:59 UTC, merged