Get and validate custom fields in funnel
threefoldtech/js-sdk pull request #1643
Opened 2020-11-08 13:44 UTC by MElborolossy

### Description

Update models, get and validate custom fields in funnel circle as described in [funnel custom fields](https://github.com/threefoldtech/circles_reporting_tool/blob/master/specs/funnel.md#custom-fields)

### Changes

- Update models with the latest specs
- Create get_issue_custom_fields function
- Create get_user_story_custom_fields functions
- Create validate_custom_fields function
- Add custom field [bookings, commission] in create_funnel_circle
- Add custom_fields as attribute in _create_new_circle function
- Update __dir__ in models.py with missed attributes and methods

### Related Issues
Resolves #1618,  Resolves #1619

### Checklist
- [ x] Build pass
- [ x] Documentation

2020-11-15 13:53 UTC, MElborolossy commented
For Export and Import, I found if we use JSON, it will be better and easier than YAML, so that we can export and import using the Rest API as [Export and Import Taiga REST API](http://taigaio.github.io/taiga-doc/dist/api.html#export-import-export-dump)

2020-11-15 15:08 UTC, xmonader approved these changes

2020-11-15 15:12 UTC, xmonader requested changes
Added some comments and let's try using gevent.event instead of threading module

2020-11-15 16:29 UTC, MElborolossy commented on jumpscale/clients/taiga/models.py
> +    def add_allowed_params(self, *args):
**allowed_params** is a list in the Taiga client that contains the parameters that will be represented as dict in to_dict() function, as we use to_dict() to export the objects, so we need to add more parameter to the same list for each model type.

2020-11-15 16:52 UTC, MElborolossy commented on jumpscale/clients/taiga/taiga.py
> +                j.exceptions.Validation('Part: ({}) is a not a valid percentage, it must be from 0% to 100%')
I will fix it the next commit

2020-11-16 13:44 UTC, MElborolossy commented on jumpscale/clients/taiga/models.py
> +    def add_allowed_params(self, *args):
BTW I will build the YAML file without using this method.

2020-11-16 21:08 UTC, MElborolossy commented on jumpscale/clients/taiga/models.py
> +        TEMPLATE = dedent(
Fix cross-linking, it is not using id.
it is using ref instead.

2020-11-17 14:20 UTC, xmonader approved these changes

2020-11-27 15:42 UTC, merged