packages frontend tests
threefoldtech/js-sdk pull request #1683
Opened 2020-11-15 07:58 UTC by Dina-Abd-Elrahman

2020-11-18 12:01 UTC, mhost39 commented on tests/frontend/tests/test_packages.py
> +        print(installed_packages, available_packages)
why print here ?

2020-11-18 12:08 UTC, mhost39 commented
Scenarios need to be covered:

- install package (like marketplace)

- open package in browser

2020-11-24 09:54 UTC, AhmedHanafy725 requested changes

2020-11-24 09:54 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +    def check_package_card(self):
Can we use a better name for this method?

2020-11-24 09:54 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +        for package in installed_packages.keys():
Instead of search in the packages, we can only check that `package_name` in `packages.keys()` and remove it, if it exists.

2020-11-25 18:59 UTC, AhmedHanafy725 reviewed
Please generate the docs for these tests, see https://github.com/threefoldtech/js-sdk/tree/development/tests#generate-tests-docs-from-scratch

2020-12-15 19:57 UTC, AhmedHanafy725 requested changes

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +            threebot_installed = 1
we can use boolean type instead of 0 and 1

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +    def check_threebot_deployer_package(self):
this method name is confusing, we are adding threebot package or checking that it is installed.

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +            system_name = system_packages_cards_name.text
```suggestion
            system_package_name = system_packages_cards_name.text
```

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +    def system_packages(self):
```suggestion
    def get_system_packages(self):
```

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +    def check_packages_type(self):
```suggestion
    def get_installed_and_available_packages(self):
```

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +            installed_name = installed_package_card_name.text
```suggestion
            installed_package_name = installed_package_card_name.text
```

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +            available_name = available_package_card_name.text
```suggestion
            available_package_name = available_package_card_name.text
```

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +    def install_package(self):
```suggestion
    def install_random_package(self):
```

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +    def chatflows(self):
this method shouldn't be working only on threebot deployer package

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_packages.py
> +        self.assertNotIn(installed_package, available_packages.keys())
please check also that the package is in the installed packages

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/pages/Packages/packages.py
> +    def open_in_browser(self):
this method shouldn't be only working on threebot deployer package

2020-12-15 19:57 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_packages.py
> +        self.info("Check that the chatflow pop-up window appears")
where is the code that pressing the chatflows button and checking that the pop-up window?

2021-01-13 12:49 UTC, AhmedHanafy725 approved these changes

2021-01-14 14:34 UTC, ramezsaeed approved these changes

2021-01-14 14:43 UTC, merged