add settings UI tests
threefoldtech/js-sdk pull request #1943
Opened 2020-12-24 08:48 UTC by mhost39

### Related Issues
https://github.com/threefoldtech/js-sdk/issues/1942

2021-01-17 14:30 UTC, AhmedHanafy725 requested changes
- Please generate the docs of these tests

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_settings.py
> +    def test04_developer_options(self):
every button should have a separate test

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        """
All tests on this module don't follow the shape of our docstring

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        self.create_wallet(self.wallet_name)
the wallet should be imported as we use one wallet for all tests

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        self.create_wallet(self.wallet_name)
`delete_wallet` instead?

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        self.info("Create a wallet")
I think it should be import wallet and the log should be in `setUpClass`

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        self.info("Delete the wallet")
this log should be in `tearDownClass`

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +    def setUp(self):
let's use `setUpClass` and `tearDownClass` for these tests.

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        self.info("Create a wallet")
the same

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        self.info("Delete the wallet")
the same

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        wallets.delete(wallet_name)
this should be removed after importing the wallet in `setUpClass`

2021-01-17 14:30 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_workloads.py
> +        """
this test doesn't follow the shape of our docstring

2021-03-01 12:12 UTC, AhmedHanafy725 requested changes
Please add a screenshot for running these tests

2021-03-01 12:12 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +        j.clients.stellar.get(cls.wallet_name, network="STD", secret=cls.wallet_secret)
Please get the wallet then change the secret as we do in vdc tests https://github.com/threefoldtech/js-sdk/blob/development/tests/sals/vdc/vdc_base.py#L37

2021-03-01 12:12 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_threebot_deployer.py
> +from tests.frontend.pages.wallets.wallets import Wallets
not needed?

2021-03-01 19:52 UTC, mhost39 commented
settings: 
![image](https://user-images.githubusercontent.com/31102305/109530080-fe138880-7abe-11eb-9831-cfc1b93e2aed.png)

explorer:
![image](https://user-images.githubusercontent.com/31102305/109530331-42068d80-7abf-11eb-8909-85816a0e7918.png)

workloads:
![image](https://user-images.githubusercontent.com/31102305/109530919-f0123780-7abf-11eb-9872-d5f87bb12258.png)

2021-03-02 14:28 UTC, AhmedHanafy725 requested changes
Please resolve the conflict in this branch,

2021-03-02 14:28 UTC, AhmedHanafy725 commented on tests/frontend/tests/test_settings.py
> +    @pytest.mark.skip("can't get inputs name")
Please open an issue and skip it with the issue link to be tracked.

2022-12-27 21:23 UTC, closed without merging