Development vdc testing billing
threefoldtech/js-sdk pull request #2288
Opened 2021-01-19 12:44 UTC by MElborolossy

### Description

Describe the changes introduced by this PR and what does it affect

### Changes

List of changes this PR includes

### Related Issues

List of related issues

### Checklist

- [ ] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-01-20 13:20 UTC, MElborolossy commented
All test passed
![image](https://user-images.githubusercontent.com/11272864/105180213-edbcd500-5b32-11eb-9006-c297fee2833b.png)

2021-01-25 13:41 UTC, waleedhammam approved these changes

2021-01-25 13:41 UTC, waleedhammam commented on tests/sals/billing/test_billing.py
> +        pass
```suggestion
        
```

2021-01-25 13:41 UTC, waleedhammam commented on tests/sals/billing/test_billing.py
> +        pass
```suggestion
        
```

2021-01-25 14:33 UTC, AhmedHanafy725 requested changes

2021-01-25 14:33 UTC, AhmedHanafy725 commented on tests/sals/billing/test_billing.py
> +        - Check that payment success state True
```suggestion
        """Test Case for processing payments.

        **Test Scenario**
        - Submit a payment with an amount of 1 TFT to the destination wallet.
        - Check that payment is submitted and success state False.
        - Transfer 1 TFT from the source wallet.
        - Run process_payments.
        - Check that payment success state True.
```

2021-01-25 14:33 UTC, AhmedHanafy725 commented on tests/sals/billing/test_billing.py
> +        - Check if refund_extra return correct amount
```suggestion
        """Test case for refunding extra payments.

        **Test Scenario**
        - Submit a payment with an amount of 1 TFT to the destination wallet.
        - Get the source wallet balance.
        - Transfer 2 TFT from the source wallet.
        - Run refund_extra.
        - Get the source wallet balance.
        - Check if refund_extra returns the correct amount.
```

2021-01-25 14:33 UTC, AhmedHanafy725 commented on tests/sals/billing/test_billing.py
> +        - Check if balance not changed
```suggestion
        """Test case for refunding extra payments and set refund_extra False.

        **Test Scenario**
        - Submit a payment with an amount of 1 TFT to destination wallet with refund_extra flag equals False.
        - Transfer 2 TFT from the source wallet.
        - Get the source wallet balance.
        - Run refund_extra.
        - Get the source wallet balance.
        - Check if the balance not changed.
```

2021-01-26 07:20 UTC, MElborolossy commented
After last commit all tests passed
![image](https://user-images.githubusercontent.com/11272864/105812951-baa59600-5fb7-11eb-816a-809e718331b1.png)

2021-01-26 09:43 UTC, AhmedHanafy725 approved these changes

2021-01-26 09:44 UTC, merged