Add More Tests for Kubernetes Sals
threefoldtech/js-sdk pull request #2301
Opened 2021-01-21 07:46 UTC by MElborolossy

### Description

Add more tests for Kubernetes sals

### Changes

- [x] get_helm_chart_user_values

### Related Issues

#2140

### Checklist

- [x] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [x] Tests included
- [x] Build pass
- [x] Documentation
- [x] Code format and docstrings

2021-01-25 13:47 UTC, waleedhammam approved these changes

2021-01-25 15:16 UTC, AhmedHanafy725 requested changes
we need to delete deployed solution in `tearDown`.

2021-01-25 15:16 UTC, AhmedHanafy725 commented on tests/sals/kubernetes/test_kubernetes.py
> +        """Test case for get the custom user values for helm chart
```suggestion
        """Test case for getting the custom user values for helm chart
```

2021-01-25 15:16 UTC, AhmedHanafy725 commented on tests/sals/kubernetes/test_kubernetes.py
> +        """Test case for upgrade helm release
```suggestion
        """Test case for upgrading helm release.
```

2021-01-25 15:16 UTC, AhmedHanafy725 commented on tests/sals/kubernetes/test_kubernetes.py
> +        """Test case for upgrade helm release with given yaml config
```suggestion
        """Test case for upgrading helm release with given yaml config.
```

2021-01-25 15:18 UTC, MElborolossy commented
The whole vdc will deleted

2021-01-25 15:20 UTC, AhmedHanafy725 commented
> The whole vdc will deleted

But it might run out of resources?

2021-01-25 15:56 UTC, MElborolossy commented
> > The whole vdc will deleted
> 
> 
> 
> But it might run out of resources? 

If it is a new vdc, it will not

2021-01-25 19:50 UTC, MElborolossy commented
After last changes, All tests passed
![image](https://user-images.githubusercontent.com/11272864/105757944-5a7f0780-5f57-11eb-962f-74a20bd6f23c.png)

2021-01-26 08:30 UTC, AhmedHanafy725 approved these changes

2021-01-26 08:31 UTC, merged