Testing vdc_dashboard chatflows
threefoldtech/js-sdk pull request #2305
Opened 2021-01-21 12:02 UTC by MElborolossy

### Description

Describe the changes introduced by this PR and what does it affect

### Changes

### Related Issues

#2201 

### Checklist

- [ ] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-02-02 05:13 UTC, MElborolossy commented
All Tests passed, except Extend Kubernetes, because payment was down, it passed before
I will try to run it again and update the status once all passed
![image](https://user-images.githubusercontent.com/11272864/106555353-1034f200-6526-11eb-9196-f2fe199d0c88.png)

2021-02-02 14:34 UTC, AhmedHanafy725 requested changes

2021-02-02 14:34 UTC, AhmedHanafy725 commented on tests/sals/automated_chatflows/test_vdc_dashboard.py
> +            if not put_hello == "":
```suggestion
            if put_hello:
```

2021-02-02 14:34 UTC, AhmedHanafy725 commented on tests/sals/automated_chatflows/test_vdc_dashboard.py
> +                is_ready = True
not used?

2021-02-02 14:34 UTC, AhmedHanafy725 commented on tests/sals/automated_chatflows/test_vdc_dashboard.py
> +        - Check that node added.
```suggestion
        """Test case for extending Kubernetes cluster.

        **Test Scenario**

        - Deploy VDC.
        - Get the number of nodes before extending.
        - Extend Kubernetes cluster.
        - Get the number of nodes after extending.
        - Check that node has been added.
```

2021-02-07 16:26 UTC, AhmedHanafy725 approved these changes

2021-02-07 16:27 UTC, merged