optimize vdc backup layout
threefoldtech/js-sdk pull request #2762
Opened 2021-03-14 14:11 UTC by samaradel

### Description

Optimze vdc backup layout

### Changes

Update headers
update timestamp format
Update create popup 
Fix typos

![image](https://user-images.githubusercontent.com/11662805/111071286-24352180-84de-11eb-920b-2789bf05f50f.png)

![image](https://user-images.githubusercontent.com/11662805/111071300-33b46a80-84de-11eb-864c-167f4e94b4f6.png)

![image](https://user-images.githubusercontent.com/11662805/111071319-46c73a80-84de-11eb-910c-96844c77698e.png)

### Related Issues

[#2752](https://github.com/threefoldtech/js-sdk/issues/2752)
### Checklist

- [ ] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-03-14 14:52 UTC, waleedhammam requested changes

2021-03-14 14:52 UTC, waleedhammam commented on jumpscale/packages/vdc_dashboard/frontend/components/vdcSettings/Backups.vue
> +      return time;
```suggestion
    return a.toLocaleString();
```

example
![Screenshot from 2021-03-14 16-51-38](https://user-images.githubusercontent.com/10658229/111072975-92311700-84e5-11eb-8ac7-bb2d1b975398.png)

2021-03-15 09:00 UTC, waleedhammam approved these changes

2021-03-15 15:28 UTC, dmahmouali approved these changes

2021-03-15 15:35 UTC, merged