Refactor VDC solution chatflows
threefoldtech/js-sdk pull request #2839
Opened 2021-03-29 12:45 UTC by dmahmouali

### Changes

- #### Refactor solution_chatflows sals
- Create a `config` object for each deployment instead of use `self` everywhere.
- The `config` object contains:
  - `username` defined in init_chatflow step.
  - `release_name` for solution name
  - `chart_config` object for all chart attributes. 
- Reordered the steps
- Add init_chatflow as a Separate step, not related to the `get_release_name` step.
- Change `choose_flavor` to be a step in the chatflow
- Define the `get_config` function to be overwritn in every chatflow to get the custom configuration

### Related Issues

- https://github.com/threefoldtech/js-sdk/issues/2791
### Checklist

- [ ] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-03-29 20:04 UTC, waleedhammam requested changes

2021-03-29 20:04 UTC, waleedhammam commented on jumpscale/packages/vdc_dashboard/chats/mattermost.py
> +        self.config.chart_config.mysql_root_password = form.secret_ask(
we need to set .value out of form.ask, because inside it'll be a for chatflow object

2021-03-29 20:04 UTC, waleedhammam commented on jumpscale/packages/vdc_dashboard/chats/peertube.py
> +        # TODO:
what's the todo ?

2021-03-29 21:32 UTC, waleedhammam approved these changes

2021-04-08 16:18 UTC, dmahmouali commented
shouldn't merge before apply changes on `mastodon`
https://github.com/threefoldtech/vdc-solutions-charts/pull/136

2021-04-13 13:12 UTC, merged