Create docs for the VDC dashboard package
threefoldtech/js-sdk pull request #2866
Opened 2021-04-04 13:53 UTC by dmahmouali

### Changes

- Create docs for the VDC dashboard package
- And for Adding new solutions chatflow its updated in this PR https://github.com/threefoldtech/js-sdk/pull/2839
### Related Issues

-  https://github.com/threefoldtech/js-sdk/issues/1924
### Checklist

- [ ] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-04-04 14:09 UTC, ranatrk requested changes

2021-04-04 14:09 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +- The frontend built with [Vue js](https://vuejs.org/) and use [vuetify js](https://vuetifyjs.com/) some components.
```suggestion
- The frontend is built with [Vue js](https://vuejs.org/) using some components from [vuetify js](https://vuetifyjs.com/).
```

2021-04-04 14:09 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +  - The user can deploy, list and delete his/her solutions.
```suggestion
  - The user can deploy, list, and delete their solutions.
```

2021-04-04 14:09 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +  - The default tab represent the `Compute Nodes` for the VDC Kubernetes cluster, The user can Add or remove the nodes.
```suggestion
  - The default tab represents the `Compute Nodes` for the VDC Kubernetes cluster where the user can add or remove nodes from their VDC.
```

2021-04-04 14:09 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +    - Add/Delete storage node.
```suggestion
    - Add/Delete storage nodes.
```

2021-04-04 14:09 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +  - In Wallet Information tab there is the prepaid wallet information.
```suggestion
  - `Wallet Information tab`: consists of the prepaid wallet information.
```

2021-04-04 14:09 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +  - The default tab represent the `Compute Nodes` for the VDC Kubernetes cluster, The user can Add or remove the nodes.
```suggestion
  - `Compute Nodes tab` is the default tab for the VDC Kubernetes cluster, where the user can add or remove their VDC's nodes.
```

2021-04-04 14:09 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +  - In the Backup And Restore tab there is a list of backups and the user can create new and restore any of them.
```suggestion
  - `Backup And Restore tab`: consists of a list of backups. It also enables the user to create new ones or restore any of the previously backed up ones.
```

2021-04-04 14:23 UTC, xmonader commented
Let's also add some info on the included services in the package.

2021-04-04 15:33 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +- `domain.py`: This service is responsible for redeploy subdomain.
```suggestion
- `domain.py`: This service is responsible for redeploying subdomains.
```

2021-04-04 15:36 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +- `etcd_backup.py`: This service is responsible for use `etcdctl` to get a snapshot of etcd and back it up using `restic`, *it stopped for now*
```suggestion
- `etcd_backup.py`: This service is responsible for backup using `etcdctl` to get a snapshot of etcd and backing it up using `restic`. [currently disabled]
```

2021-04-04 15:37 UTC, ranatrk commented on docs/vdc/vdc_dashboard.md
> +- `zdb_auto_topup.py`: This service is responsible for extend the VDC ZDBs capacity.
```suggestion
- `k8s_auto_extend.py`: This service is responsible for auto extending the kubernetes cluster to its plan limits if needed.
- `provisioning_wallet_billing.py`: This service is responsible for extending the VDC pool.
- `s3_auto_topup.py`: *it stopped for now*
- `transaction_from_prepain_to_provisioning.py`: This service is responsible for transfering funds from the prepaid to the provision wallet
- `zdb_auto_topup.py`: This service is responsible for extending the VDC ZDB's capacity.
```

2021-04-04 15:45 UTC, ranatrk approved these changes

2021-04-05 07:02 UTC, xmonader approved these changes

2021-04-05 07:02 UTC, merged