VDC Backup and Restore listing
threefoldtech/js-sdk pull request #2869
Opened 2021-04-05 14:11 UTC by MElborolossy

### Description

Refactor VDC Backup and Restore listing to list backup as 1 item, not 2 items

### Related Issues

#2789

### Checklist

- [x] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-04-05 14:54 UTC, ranatrk approved these changes

2021-04-07 07:57 UTC, AhmedHanafy725 requested changes

2021-04-07 08:37 UTC, MElborolossy commented on jumpscale/packages/vdc_dashboard/bottle/backup.py
> +                backup = backup_2
It always views that Backup metadata only
So, I make this condition

2021-04-07 09:43 UTC, AhmedHanafy725 approved these changes

2021-04-07 10:11 UTC, dmahmouali approved these changes

2021-04-07 10:12 UTC, merged