Fix farmedit modal
threefoldtech/js-sdk pull request #3002
Opened 2021-04-26 10:18 UTC by samaradel

### Description

Fix delete request 

### Changes

- Display IP in delete modal
- Fix delete request

### Related Issues

[#2701](https://github.com/threefoldtech/js-sdk/issues/2701)

### Checklist

- [ ] [Pre-commit hook is installed](https://github.com/threefoldtech/js-ng#pre-commit) to do formatting checks before committing code...etc
- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2021-04-26 10:23 UTC, waleedhammam requested changes

2021-04-26 10:23 UTC, waleedhammam commented on jumpscale/packages/vdc/package.toml
> -letsencryptemail = "motaweam@incubaid.com"
need to bring back, we can leave values empty

2021-04-26 10:23 UTC, waleedhammam commented on jumpscale/sals/vdc/wallet.py
> +        #instance._init_wallet()
need to bring back

2021-04-26 10:23 UTC, waleedhammam commented on jumpscale/packages/threebot_deployer/package.toml
> -letsencryptemail = "motaweam@incubaid.com"
need to bring back, we can leave values empty

2021-04-26 10:23 UTC, waleedhammam commented on jumpscale/packages/farmmanagement/frontend/views/farmedit/farmedit.js
> +                console.log(ipaddress)
```suggestion
```

2021-04-26 10:31 UTC, waleedhammam approved these changes

2021-05-05 12:16 UTC, rkhamis approved these changes

2021-05-19 10:09 UTC, merged